Vagrant.configure(2) do |config|
  config.vm.define "controller" do |node|
        node.vm.box = "centos/7"
        node.vm.hostname = "controller"
        node.vm.network :private_network, ip: "192.168.33.11"
        node.vm.network :forwarded_port, id: "ssh", guest: 22, host: 2210
  end
  config.vm.define "target1" do |node|
        node.vm.box = "centos/7"
        node.vm.hostname = "target1"
        node.vm.network :private_network, ip: "192.168.33.20"
        node.vm.network :forwarded_port, id: "ssh", guest: 22, host: 2220
  end
 config.vm.define "target2" do |node|
        node.vm.box = "centos/7"
        node.vm.hostname = "target2"
        node.vm.network :private_network, ip: "192.168.33.21"
        node.vm.network :forwarded_port, id: "ssh", guest: 22, host: 2230
  end
end
